"""Emission of portable semantic MLIR for a contraction.

The emitter deliberately stops at `linalg.generic`. Target-specific plan
lowering belongs to a later pipeline stage: Direct lowers the generic op, while
GEMM plans replace it with view/pack operations and a runtime library call.
Keeping semantic emission separate makes it golden-testable without LLVM/MLIR
installed on the development Mac.
"""

from __future__ import annotations

from dataclasses import dataclass
import re
from typing import Sequence, Tuple

from .problem import ContractionProblem, TensorSpec


_BARE_SYMBOL = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _tensor_type(spec: TensorSpec) -> str:
    if not spec.shape:
        return "tensor<f32>"
    dimensions = "x".join(str(extent) for extent in spec.shape)
    return "tensor<{}xf32>".format(dimensions)


def _affine_map(loop_labels: Sequence[str], operand_labels: Sequence[str]) -> str:
    positions = {label: index for index, label in enumerate(loop_labels)}
    domain = ", ".join("d{}".format(index) for index in range(len(loop_labels)))
    results = ", ".join("d{}".format(positions[label]) for label in operand_labels)
    return "affine_map<({})->({})>".format(domain, results)


@dataclass(frozen=True)
class MlirModule:
    text: str
    loop_labels: Tuple[str, ...]


class MlirEmitter:
    """Translate target-independent IR to a `linalg.generic` module."""

    def emit(self, problem: ContractionProblem, function_name: str = "contract") -> MlirModule:
        if not _BARE_SYMBOL.fullmatch(function_name):
            raise ValueError(
                "function name must be an ASCII MLIR symbol beginning with a letter or underscore"
            )

        loop_labels = problem.equation.output + problem.groups.reduction
        lhs_map = _affine_map(loop_labels, problem.equation.lhs)
        rhs_map = _affine_map(loop_labels, problem.equation.rhs)
        output_map = _affine_map(loop_labels, problem.equation.output)
        iterators = ["parallel"] * len(problem.equation.output) + [
            "reduction"
        ] * len(problem.groups.reduction)
        iterator_text = ", ".join('"{}"'.format(value) for value in iterators)

        lhs_type = _tensor_type(problem.lhs)
        rhs_type = _tensor_type(problem.rhs)
        output_type = _tensor_type(problem.output)
        lines = [
            "// Generated by EinsumCC Nano v1.",
            "// equation: {}".format(problem.equation.text),
            "// loop order: {}".format(" ".join(loop_labels)),
            "module {",
            "  func.func @{}(%lhs: {}, %rhs: {}) -> {} {{".format(
                function_name, lhs_type, rhs_type, output_type
            ),
            "    %empty = tensor.empty() : {}".format(output_type),
            "    %zero = arith.constant 0.0 : f32",
            "    %init = linalg.fill ins(%zero : f32) outs(%empty : {}) -> {}".format(
                output_type, output_type
            ),
            "    %result = linalg.generic {",
            "      indexing_maps = [{}, {}, {}],".format(lhs_map, rhs_map, output_map),
            "      iterator_types = [{}]".format(iterator_text),
            "    }} ins(%lhs, %rhs : {}, {}) outs(%init : {}) {{".format(
                lhs_type, rhs_type, output_type
            ),
            "    ^bb0(%lhs_value: f32, %rhs_value: f32, %accumulator: f32):",
            "      %product = arith.mulf %lhs_value, %rhs_value : f32",
            "      %sum = arith.addf %accumulator, %product : f32",
            "      linalg.yield %sum : f32",
            "    }} -> {}".format(output_type),
            "    return %result : {}".format(output_type),
            "  }",
            "}",
            "",
        ]
        return MlirModule("\n".join(lines), loop_labels)
