"""Emission of EinsumCC's target-independent ``tc.contract`` IR.

This is the real frontend/backend boundary.  The Python frontend owns Einstein
syntax and shape/layout analysis; the C++ dialect owns IR verification and
lowering.  Keeping the textual bridge deterministic also makes every frontend
decision reviewable in tests and compiler dumps.
"""

from __future__ import annotations

from dataclasses import dataclass
import re
from typing import Sequence, Tuple

from .problem import ContractionProblem, TensorSpec


_BARE_SYMBOL = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _tensor_type(spec: TensorSpec) -> str:
    if not spec.shape:
        return "tensor<f32>"
    return "tensor<{}xf32>".format("x".join(str(value) for value in spec.shape))


def _affine_map(loop_labels: Sequence[str], operand_labels: Sequence[str]) -> str:
    positions = {label: index for index, label in enumerate(loop_labels)}
    domain = ", ".join("d{}".format(index) for index in range(len(loop_labels)))
    results = ", ".join("d{}".format(positions[label]) for label in operand_labels)
    return "affine_map<({})->({})>".format(domain, results)


@dataclass(frozen=True)
class TcModule:
    text: str
    loop_labels: Tuple[str, ...]


class TcEmitter:
    """Translate a verified contraction problem to one ``tc.contract``."""

    def emit(
        self,
        problem: ContractionProblem,
        function_name: str = "contract",
        *,
        emit_c_interface: bool = False,
    ) -> TcModule:
        if not _BARE_SYMBOL.fullmatch(function_name):
            raise ValueError(
                "function name must be an ASCII MLIR symbol beginning with a letter or underscore"
            )

        loops = problem.equation.output + problem.groups.reduction
        maps = (
            _affine_map(loops, problem.equation.lhs),
            _affine_map(loops, problem.equation.rhs),
            _affine_map(loops, problem.equation.output),
        )
        iterators = ("parallel",) * len(problem.equation.output) + (
            "reduction",
        ) * len(problem.groups.reduction)
        lhs_type = _tensor_type(problem.lhs)
        rhs_type = _tensor_type(problem.rhs)
        result_type = _tensor_type(problem.output)
        iterator_text = ", ".join('"{}"'.format(value) for value in iterators)
        function_attributes = (
            " attributes {llvm.emit_c_interface}" if emit_c_interface else ""
        )
        lines = [
            "// Generated by the EinsumCC Einstein frontend.",
            "module {",
            "  func.func @{}(%lhs: {}, %rhs: {}) -> {}{} {{".format(
                function_name, lhs_type, rhs_type, result_type, function_attributes
            ),
            "    %result = tc.contract %lhs, %rhs {",
            '      equation = "{}",'.format(problem.equation.text),
            "      indexing_maps = [{}, {}, {}],".format(*maps),
            "      iterator_types = [{}]".format(iterator_text),
            "    }} : ({}, {}) -> {}".format(lhs_type, rhs_type, result_type),
            "    return %result : {}".format(result_type),
            "  }",
            "}",
            "",
        ]
        return TcModule("\n".join(lines), loops)
